### ISSUE TITLE
Too many connection

### ISSUE THREAD

**Issue by channaveer** [sidorares/node-mysql2#2362]
**OS:** Ubuntu 22.04 LTS
**MySQL:** 8.0.35
**NodeJS:** 20.10.0
**NPM:** 10.2.3
**mysql2:** ^3.7.0

**MySQL: total threads available in my system**

```
mysql> SHOW VARIABLES LIKE 'max_connections';
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 151   |
+-----------------+-------+
1 row in set (0.00 sec)
```

**MySQL: At any given time if I wanna see the total threads used**

```
mysql> SHOW STATUS LIKE 'Threads_connected';
+-------------------+-------+
| Variable_name     | Value |
+-------------------+-------+
| Threads_connected | 149   |
+-------------------+-------+
1 row in set (0.00 sec)
```

Following is my project structure

```
/node-mysql
    app.js
    index.js
    /src
        /database
            mysql.js
        /cronjobs
            /** Cronjobs are run from the crontab /
            natlog.cron.js
```

**mysql.js**
--------
```js
require("dotenv").config();
const mysql = require("mysql2/promise");

/**
 * Connection Pool
 * Connection pools help reduce the time spent connecting to the MySQL server by reusing a previous connection leaving them open instead of closing when you are done with them.
 */

const mysqlConnection = mysql.createPool({
    host: process.env.DB_NATLOG_MYSQL_HOST,
    user: process.env.DB_NATLOG_MYSQL_USERNAME,
    password: process.env.DB_NATLOG_MYSQL_PASSWORD,
    database: process.env.DB_NATLOG_MYSQL_DATABASE,
    waitForConnections: true,
    connectionLimit: 20,
    queueLimit: 0,
    enableKeepAlive: true,
    keepAliveInitialDelay: 0,
});

mysqlConnection.on('acquire', function (connection) {
    console.log('Connection %d acquired', connection.threadId);
});

mysqlConnection.on('enqueue', function () {
console.log('Waiting for available connection slot');
});

mysqlConnection.on('release', function (connection) {
console.log('Connection %d released', connection.threadId);
});

module.exports = mysqlConnection;
```

I am using the mysql.js in the following file

**natlog.cron.js**
--------------

```js
require("dotenv").config();
const { dateHelper } = require("../helpers");
const mysqlConnection = require("../database/mysql");

async function runConntrackAndSaveToLog() {
    try {
        const currentDate = dateHelper.currentDateInYYYMMDD();
    
        const natlogs = extractConnections(data);

        if (natlogs) {
            for await (const natlog of natlogs) {
                if (natlog.mac.includes("incomplete")) {
                    continue;
                }

                natlogValues += `
                    (
                        "${natlog.src}",
                        "${natlog.dst}",
                        "${natlog.sport}",
                        "${natlog.dport}",
                        "${natlog.mac}"
                    ),
                `;
            }

            /** Remove the last comma of the values */
            natlogValues = natlogValues.replace(/,(?=\s*$)/, '');

            const natlogQuery = `
                INSERT INTO \`${currentDate}\`
                    (
                        src_ip,
                        dest_ip,
                        src_port,
                        dest_port,
                        user_mac_address
                    )
                VALUES
                    ${natlogValues}
            `;

            await mysqlConnection.query(natlogQuery);
        }
    } catch (error) {
        console.log({
            location: "Natlog cronjob error",
            message: error.message,
            stack: error.stack,
        });
    }
}

(async () => {
    console.log("CronJob: Nat Log...");
    await runConntrackAndSaveToLog();
})();
```

I am calling cronjob every everyminute which runs the above code but for some reason the connection process are being overflown

```bash
* * * * * (cd /home/chan/node-mysql && /home/chan/.nvm/versions/node/v20.10.0/bin/node src/cronjobs/natlog.cron.js) 2>&1
```

**ERROR**

```
/home/chan/node-mysql/node_modules/mysql2/promise.js:356
    const localErr = new Error();
                     ^

Error: Too many connections
    at PromisePool.query (/home/chan/node-mysql/node_modules/mysql2/promise.js:356:22)
    at createNatlogTableIfNotExists (/home/chan/node-mysql/src/cronjobs/natlog.cron.js:11:33)
    at /home/chan/node-mysql/src/cronjobs/natlog.cron.js:45:27
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
  code: 'ER_CON_COUNT_ERROR',
  errno: 1040,
  sql: undefined,
  sqlState: '',
  sqlMessage: 'Too many connections'
}
```

**Comment by Ejayz** [comment]
Hi . I have the same problem . Have you check mysql server monitoring if like connection stops but process keeps on increasing ? I noticed that connection is getting closed but the process keeps increasing in my mysql server.

**Comment by channaveer** [comment]
@Ejayz yes this happened with me. I tried with pool connection and releasing the connection too, but as you said the connection is released but the thread count keeps increasing and after reaching limit everything dies. I had to restart MySQL service to login to terminal.

For time being I had to fallback to createConnection code and in the end I am releasing the connection. This one is working fine. But make sure to restart MySQL service so that the threads that are already stuck gets released and works well.

**Comment by Ejayz** [comment]
Hmmmm i see . Welp probly this is a bug or something . When would this be fixed thats the question .

**Comment by wifidabba** [comment]
@Ejayz Not sure on that part. Good to fallback to old version on **mysql2** where this error was not encountered.  

Or better to go ahead without connection pool for time being, but again it depends on individual's requirements.

**Comment by Ejayz** [comment]
Welp idk what are the pros and cons of using createConnection vs createPool @wifidabba but if there are no options then it is createConnection for now . Hope it would have update about this . stopping connection on createPool will also show error. But dont you think we can do some checking on ``Connection.On`` method ? like monitor it and close this threads?

**Comment by Ejayz** [comment]
This is still happening in ``createConnection`` . It does not drop threads and keeps on increasing even i have ``connection.destroy()`` anyidea how to stop this threads after the query? we can get ``threadId`` can we manually stop that threads using that thread id

**Comment by Ejayz** [comment]
hi @channaveer . I asked on one of nextjs community and it seems i find one of the solution . Create a singleton that will be used the same instance of connection instead of creating multiple instance each import . [https://www.prisma.io/docs/orm/more/help-and-troubleshooting/help-articles/nextjs-prisma-client-dev-practices#solution](url) This is his refference that he sent to my . Though this is the code i made chat gpt generated and seems to work fine ```
import mysql, { Pool, PoolConnection } from 'mysql2/promise';
const { DB_HOST, DB_USER, DB_PASSWORD, DB_NAME } = process.env;

export class Connection {
  private static instance: Connection;
  private pool: Pool;

  private constructor() {
    console.log('Creating MySQLPoolSingleton instance'); // Add this line
    // Set up your MySQL connection pool parameters
    const poolConfig: mysql.PoolOptions = {
      host: DB_HOST,
    user: DB_USER,
    password: DB_PASSWORD,
    database: DB_NAME,
    waitForConnections: true,
    connectionLimit: 10,
    idleTimeout: 5000,
    queueLimit: 0,
    };

    this.pool = mysql.createPool(poolConfig);
  }

  public static getInstance(): Connection {
    if (!Connection.instance) {
      Connection.instance = new Connection();
    }

    return Connection.instance;
  }

  public async getConnection(): Promise<PoolConnection> {
    return this.pool.getConnection();
  }

  // You can add other methods or configurations as needed

  public async closePool(): Promise<void> {
    await this.pool.end();
  }
}

``` 
PS: yea i made chat gpt generate it . 

Anyways a singleton sample on documentation would be good for samples on js. since most of files i guess are imported and recreated a connection

**Comment by wifidabba** [comment]
> This is still happening in `createConnection` . It does not drop threads and keeps on increasing even i have `connection.destroy()` anyidea how to stop this threads after the query? we can get `threadId` can we manually stop that threads using that thread id

As soon as after my query is completed I am ending the connection in the following manner and its working for me. If you are working on the medium to bigger project then I think going ahead with your singleton solution for time being is good one.

```
/** Other code */
const natlogQuery = `MY QUERY`;

(await mysqlConnection).query(natlogQuery);

(await mysqlConnection).end();
```

**Comment by channaveer** [comment]
> This is still happening in `createConnection` . It does not drop threads and keeps on increasing even i have `connection.destroy()` anyidea how to stop this threads after the query? we can get `threadId` can we manually stop that threads using that thread id

As soon as after my query is completed I am ending the connection in the following manner and its working for me. If you are working on the medium to bigger project then I think going ahead with your singleton solution for time being is good one.

```
/** Other code */
const natlogQuery = `MY QUERY`;

(await mysqlConnection).query(natlogQuery);

(await mysqlConnection).end();
```

**Comment by Ejayz** [comment]
Do you think hot reload will invalidate single ton ?

**Comment by channaveer** [comment]
As you mentioned that you had posted in NextJS forum which means you might be using NextJS, So probably the hot reload might invalidate the singleton. But kindly check the thread if the thread acquired are being released or not by login to MySQL cli or any MySQL client with the following command


```
SHOW STATUS LIKE 'Threads_connected'
```

**Comment by Ejayz** [comment]
> As you mentioned that you had posted in NextJS forum which means you might be using NextJS, So probably the hot reload might invalidate the singleton. But kindly check the thread if the thread acquired are being released or not by login to MySQL cli or any MySQL client with the following command
> 
> ```
> SHOW STATUS LIKE 'Threads_connected'
> ```

Already fixed by creating a global variable . Thanks

**Comment by channaveer** [comment]
But still the problem persists for createPool as the threads are not being released after conn.query is finished executing the query. The issue has to be rectified and solved in the library.

**Comment by Ejayz** [comment]
> But still the problem persists for createPool as the threads are not being released after conn.query is finished executing the query. The issue has to be rectified and solved in the library.

After creating a singleton and putting a global variable it seems to be working fine. Probly update on how to use the library will be a good step since most of javascript framework do Hot Reload which will I think cause the problem . A didicated tutorial on how to create a class or function that will create the connection and a file that will assign the connection to global variable and return it if available.

**Comment by channaveer** [comment]
> > But still the problem persists for createPool as the threads are not being released after conn.query is finished executing the query. The issue has to be rectified and solved in the library.
> 
> After creating a singleton and putting a global variable it seems to be working fine. Probly update on how to use the library will be a good step since most of javascript framework do Hot Reload which will I think cause the problem . A didicated tutorial on how to create a class or function that will create the connection and a file that will assign the connection to global variable and return it if available.

Good thought. Would you like to update the docs and send a PR to team, that would be amazing as you have the complete example with context on the same.

**Comment by Ejayz** [comment]
> > > But still the problem persists for createPool as the threads are not being released after conn.query is finished executing the query. The issue has to be rectified and solved in the library.
> > 
> > 
> > After creating a singleton and putting a global variable it seems to be working fine. Probly update on how to use the library will be a good step since most of javascript framework do Hot Reload which will I think cause the problem . A didicated tutorial on how to create a class or function that will create the connection and a file that will assign the connection to global variable and return it if available.
> 
> Good thought. Would you like to update the docs and send a PR to team, that would be amazing as you have the complete example with context on the same.

idk how to created docs or tutorial mostly informative one . but this are the code i have 

**connectionClass.ts**

```
import mysql, { Pool, PoolConnection } from 'mysql2/promise';
const { DB_HOST, DB_USER, DB_PASSWORD, DB_NAME } = process.env;

export  class Connection {
  private static instance: Connection;
  private pool: Pool;

  private constructor() {
    // Set up your MySQL connection pool parameters
    const poolConfig: mysql.PoolOptions = {
      host: DB_HOST,
    user: DB_USER,
    password: DB_PASSWORD,
    database: DB_NAME,
    waitForConnections: true,
    connectionLimit: 10,
    idleTimeout: 5000,
    queueLimit: 0,
    };

    this.pool = mysql.createPool(poolConfig);
  }

  public static getInstance(): Connection {
    if (!this.instance) {
      this.instance = new Connection();
    }

    return this.instance;
  }

  public async getConnection(): Promise<PoolConnection> {
    return this.pool.getConnection();
  }

  // You can add other methods or configurations as needed

  public async closePool(): Promise<void> {
    await this.pool.end();
  }
}
```

**db.ts**

```
import {Connection} from "./connectionClass";
declare global {
  var instance: undefined | Connection;
}

const instance=globalThis.instance ?? Connection.getInstance();
console.log("Node Env",process.env.NODE_ENV);
if (process.env.NODE_ENV !== 'production') globalThis.instance=instance;
export default  instance;
```

That are the codes . idk how others would implement this but that is the way i did.

**Comment by lgaieta** [comment]
Hi! I'm having the same error. I figured out that when I use the NextJS development server, creates a lot of db connections, even when I'm using pool connection. So after some queries, the mysql server crashes with the "Too many connections" error. But the interesting thing is that when I close my development server, the error disappears. So I think that NextJS development server (maybe hot reload) in some way skips connection release. Also when I do it on production build, everything works ok and there are not more than 2 connections created. I tested this using the SHOW STATUS LIKE 'Threads_connected'; query.
Maybe a solution is to restart the mysql server before deploying, hope this information helps!

**Comment by salik-dev** [comment]
I am using the express NodeJS server and same issue with me. in MySQL server their are a lot of process with sleep query . and the server become overload. here is my code .


```const mysql =  require('mysql2/promise');
const config = require("../../config.json");

const { database,host, user, password } = config.database;

// Create the connection pool. The pool-specific settings are the defaults
const pool = mysql.createPool({
  host: host,
  user: user,
  database: database,
  password:password,
  waitForConnections: true,
  connectionLimit: 100,
  connectTimeout:10000,
  queueLimit:20,
  maxIdle: 10,
  idleTimeout: 1000,
  enableKeepAlive: true,
  keepAliveInitialDelay: 0,
});

module.exports = pool;
```

here is my simple search function 

```async function search(params) {
	console.log("I AM HERE");

	let connection = ''
	try {
		connection = await pool.getConnection();

		let appUserResponse = await checkifAppUser(params, connection)
		if (appUserResponse != null) {
			return appUserResponse
		} else {
			let db1Response = await getContactDetailsFromDatabase1(params, connection)
			if (db1Response != null) {
				return db1Response
			} else {
				let db2Response = await getContactDetailsFromDatabase2(params, connection)
				if (db2Response != null) {
					return db2Response
				} else {
					return {
						"status": false,
						"db": "db2",
						
						"location_info": "Mobile, Newtork"
					}
				}
			}
		}


	} catch (err) {
		return {
			"status": false,
			"db": "db2",
			
			"location_info": "Mobile, Newtork"
		}
	} finally {
		if (connection) {
			console.log("Releasing connection ,Search Number");
			connection.release()
		}
	}

}```

**Comment by zoobibackups** [comment]
my pool setting . 

```const mysql =  require('mysql2/promise');
const config = require("../../config.json");

const { database,host, user, password } = config.database;
const pool = mysql.createPool({
  host: host,
  user: user,
  database: database,
  password:password,
  waitForConnections: true,
  connectionLimit: 100,
  connectTimeout:5000,
  queueLimit:20,
  maxIdle: 10,
  idleTimeout: 1000,
  enableKeepAlive: true,
  keepAliveInitialDelay: 0,
});

module.exports = pool;
```

```async function searchResults(params) {
	let connection = null
	try {
		connection = await pool.getConnection()
		let db2Response = null;
		const [results, metadata] = await connection.query(
			`SELECT id , pName from contactsdb where nationalNumber = '${params.umr}' and countryId = 167 LIMIT 1`
		);
		if (results.length > 0) {
			db2Response = {
				status: true,
				results: results

			};
		} else {
			db2Response = {
				status: false,
				results: []

			};
		}
	} catch (error) {
		db2Response = {
			status: false,
			results: []

		};
	} finally {
		if (connection) {
			connection.release()
		}
	}
	return db2Response
}```

**Comment by salik-dev** [comment]
/
