### ISSUE TITLE
Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by anjansom** [sidorares/node-mysql2#868]
Hello,

First of all, thanks @sidorares for all the good work you've been putting in this package! I've looked around at other issues but can't seem to find a valid answer for this issue.

My app queries every morning a DB and I get this error 50% of mornings as I guess the connection timedout but my mysql2 connection pool normally closes each connection after it uses it so don't know why it tries to query on a timedout connection.

Stack trace:

```
Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:402:12)
    at PoolConnection.connection.write (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:387:20)
    at PoolConnection.Connection.writePacket (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:304:10)
    at Query.start (/opt/test_api_sandbox/node_modules/mysql2/lib/commands/query.js:48:14)
    at Query.Command.execute (/opt/test_api_sandbox/node_modules/mysql2/lib/commands/command.js:40:20)
    at PoolConnection.Connection.handlePacket (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:513:28
    at PoolConnection.Connection.addCommand (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:534:10)
    at PoolConnection.query (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:623:15)
    at /opt/test_api_sandbox/node_modules/mysql2/lib/pool.js:166:10
    at /opt/test_api_sandbox/node_modules/mysql2/lib/pool.js:42:14
(node:9571) UnhandledPromiseRejectionWarning: Error: This socket has been ended by the other party
    at TLSSocket.writeAfterFIN [as write] (net.js:402:12)
    at PoolConnection.connection.write (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:387:20)
    at PoolConnection.Connection.writePacket (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:304:10)
    at Query.start (/opt/test_api_sandbox/node_modules/mysql2/lib/commands/query.js:48:14)
    at Query.Command.execute (/opt/test_api_sandbox/node_modules/mysql2/lib/commands/command.js:40:20)
    at PoolConnection.Connection.handlePacket (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:513:28
    at PoolConnection.Connection.addCommand (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:534:10)
    at PoolConnection.query (/opt/test_api_sandbox/node_modules/mysql2/lib/connection.js:623:15)
    at /opt/test_api_sandbox/node_modules/mysql2/lib/pool.js:166:10
    at /opt/test_api_sandbox/node_modules/mysql2/lib/pool.js:42:14
```

my database handler file:
```
const mysql = require('mysql2/promise');
const fs = require('fs');
require('dotenv').load();

const pool  = mysql.createPool({
        host: process.env.DB_HOST,
        user: process.env.DB_USER,
        password: process.env.DB_PASS,
        database: process.env.DB_NAME,
        ssl: {
            ca: fs.readFileSync(process.env.DB_SSL_CA),
            key: fs.readFileSync(process.env.DB_SSL_KEY),
            cert: fs.readFileSync(process.env.DB_SSL_CERT)
        },
        multipleStatements: true
});

module.exports.query = function (query, value) {
        let connection;

        return pool.getConnection().then(conn => {
            connection = conn;
            return connection.query(query, value);
        })
        .then(res => res[0])
        .catch(err => err)
        .then(res => {
            connection.release();
            return res;
        });
};
```

I use mysql2 ^1.6.1

As you see, at the end of each query I release the connection so this means there should be any idle connection which can timeout right?

Thanks
Anjan

**Comment by bonbonio** [comment]
Hi @anjansom this issue has been solved in the following pull request (https://github.com/sidorares/node-mysql2/pull/867), we are just awaiting an update of the library to be pushed to npm.

@sidorares This is a critical bug to me, and others it would appear, could we expedite the next release of mysql2 with the fix included?

**Comment by sidorares** [comment]
@bonbonio  @anjansom just published v1.6.2, let me know if that fixes your issue

**Comment by iwikal** [comment]
@sidorares v1.6.2 seems to be missing this fix, among other commits: https://github.com/sidorares/node-mysql2/compare/v1.6.2...master

**Comment by anjansom** [comment]
Great! thanks I'll make it run a few days and I'll come back to you with my findings.

**Comment by bonbonio** [comment]
@anjansom @sidorares Looks like the issue is fixed, if anything contradicts that analysis I will reply again, but so far so good.

**Comment by theFroh** [comment]
I'm using `"mysql2": "^1.6.4" on Google App Engine, and I'm still receiving this issue. 

I had assumed it was occurring when mysqld's `wait_timeout` of 60 (seconds) closes an idle pool connection, but this is definitely not the case, as the connection pool happily notes the connection as dead and opens a fresh one without issue. Ditto if, on the server, I `kill nnnnn` the connection myself.

Not too sure what might be causing this.
